import { Color, PresetPattern } from "@/types/inkle";

export const ALL_COLORS: Color[] = [
  { name: "White", hex: "#FFFFFF", owned: true },
  { name: "Cream", hex: "#ebe6d4", owned: true },
  { name: "Antique White", hex: "#e7e2dd", owned: true },
  { name: "Natural", hex: "#D3D3D3", owned: true },
  { name: "Silver", hex: "#C0C0C0", owned: false },
  { name: "Stone", hex: "#818086", owned: false },
  { name: "Black", hex: "#000000", owned: true },
  { name: "Victory Red", hex: "#77142a", owned: true },
  { name: "Burgundy", hex: "#800020", owned: false },
  { name: "Cardinal Red", hex: "#C41E3A", owned: false },
  { name: "Atom Red", hex: "#E50C21", owned: false },
  { name: "Bright Coral", hex: "#FF4040", owned: false },
  { name: "Tomato", hex: "#FF6347", owned: false },
  { name: "Orchid Pink", hex: "#F4C2C2", owned: false },
  { name: "Copper Mist", hex: "#DA8A67", owned: false },
  { name: "Pumpkin", hex: "#FF7518", owned: false },
  { name: "Fudge Brown", hex: "#5C4033", owned: false },
  { name: "Taupe", hex: "#856a5e", owned: true },
  { name: "Light Peach", hex: "#FFE5B4", owned: false },
  { name: "Goldenrod", hex: "#f5ce56", owned: true },
  { name: "Golden Yellow", hex: "#FFDF00", owned: false },
  { name: "Maize", hex: "#FBEC5D", owned: false },
  { name: "Ecru", hex: "#C2B280", owned: false },
  { name: "Wasabi", hex: "#95aa64", owned: true },
  { name: "Frosty Green", hex: "#a9b79f", owned: true },
  { name: "Myrtle Green", hex: "#336621", owned: true },
  { name: "Forest Green", hex: "#228B22", owned: false },
  { name: "Mint Green", hex: "#98FB98", owned: false },
  { name: "Parakeet", hex: "#7FFFD4", owned: false },
  { name: "Aqua", hex: "#b1dbda", owned: true },
  { name: "Peacock", hex: "#0D98BA", owned: false },
  { name: "Delft", hex: "#a6b9db", owned: true },
  { name: "Dark Royal Blue", hex: "#002366", owned: false },
  { name: "Navy Blue", hex: "#101f4f", owned: true },
  { name: "Blue Hawaii", hex: "#375cad", owned: true },
  { name: "Medium Blue", hex: "#4F709C", owned: false },
  { name: "Violet", hex: "#8A2BE2", owned: false },
  { name: "Wood Violet", hex: "#856088", owned: false },
  { name: "Purple", hex: "#800080", owned: false },
  { name: "Soft Mauve", hex: "#E0889B", owned: false },
  { name: "Hot Pink", hex: "#FF69B4", owned: false },
  { name: "French Rose", hex: "#F64A8A", owned: false },
];

export const presetPatterns: PresetPattern[] = [
  {
    name: "Dots and Squares",
    band: [
      {
        label: "H",
        colors: [
          ALL_COLORS[20],
          null,
          ALL_COLORS[20],
          null,
          ALL_COLORS[30],
          null,
          ALL_COLORS[20],
          null,
          ALL_COLORS[30],
          null,
          ALL_COLORS[20],
        ],
      },
      {
        label: "U",
        colors: [
          null,
          ALL_COLORS[20],
          null,
          ALL_COLORS[20],
          null,
          ALL_COLORS[20],
          null,
          ALL_COLORS[20],
          null,
          ALL_COLORS[20],
          null,
        ],
      },
    ],
    repeaters: [
      { count: 2, start: 5, length: 2 },
      { count: 2, start: 7, length: 2 },
      { count: 2, start: 9, length: 2 },
      { count: 3, start: 3, length: 4 },
      { count: 3, start: 7, length: 4 },
    ],
  },
  {
    name: "Offset Bars",
    band: [
      {
        label: "H",
        colors: [
          ALL_COLORS[20],
          null,
          ALL_COLORS[30],
          null,
          ALL_COLORS[20],
          null,
          ALL_COLORS[20],
          null,
          ALL_COLORS[30],
          null,
          ALL_COLORS[20],
          null,
          ALL_COLORS[20],
        ],
      },
      {
        label: "U",
        colors: [
          null,
          ALL_COLORS[20],
          null,
          ALL_COLORS[20],
          null,
          ALL_COLORS[30],
          null,
          ALL_COLORS[20],
          null,
          ALL_COLORS[20],
          null,
          ALL_COLORS[20],
          null,
        ],
      },
    ],
    repeaters: [
      { count: 2, start: 0, length: 2 },
      { count: 5, start: 2, length: 2 },
      { count: 5, start: 4, length: 2 },
      { count: 5, start: 8, length: 2 },
    ],
  },
  {
    name: "False Checks with 2",
    band: [
      {
        label: "H",
        colors: [
          ALL_COLORS[20],
          null,
          ALL_COLORS[20],
          null,
          ALL_COLORS[30],
          null,
          ALL_COLORS[20],
          null,
          ALL_COLORS[20],
        ],
      },
      {
        label: "U",
        colors: [
          null,
          ALL_COLORS[20],
          null,
          ALL_COLORS[20],
          null,
          ALL_COLORS[30],
          null,
          ALL_COLORS[20],
          null,
        ],
      },
    ],
    repeaters: [
      { count: 2, start: 3, length: 2 },
      { count: 2, start: 5, length: 2 },
      { count: 4, start: 3, length: 4 },
    ],
  },
  {
    name: "True Checks with 3",
    band: [
      {
        label: "H",
        colors: [
          ALL_COLORS[20],
          null,
          ALL_COLORS[20],
          null,
          ALL_COLORS[30],
          null,
          ALL_COLORS[20],
          null,
          ALL_COLORS[30],
          null,
          ALL_COLORS[20],
        ],
      },
      {
        label: "U",
        colors: [
          null,
          ALL_COLORS[20],
          null,
          ALL_COLORS[20],
          null,
          ALL_COLORS[30],
          null,
          ALL_COLORS[20],
          null,
          ALL_COLORS[20],
          null,
        ],
      },
    ],
    repeaters: [
      { count: 3, start: 3, length: 2 },
      { count: 2, start: 3, length: 4 },
      { count: 3, start: 5, length: 2 },
      { count: 3, start: 7, length: 2 },
    ],
  },
  {
    name: "Triple Stripes",
    band: [
      {
        label: "H",
        colors: [
          ALL_COLORS[29],
          null,
          ALL_COLORS[29],
          null,
          ALL_COLORS[35],
          null,
          ALL_COLORS[35],
          null,
          ALL_COLORS[35],
          null,
          ALL_COLORS[29],
          null,
          ALL_COLORS[29],
          null,
          ALL_COLORS[29],
        ],
      },
      {
        label: "U",
        colors: [
          null,
          ALL_COLORS[29],
          null,
          ALL_COLORS[35],
          null,
          ALL_COLORS[35],
          null,
          ALL_COLORS[35],
          null,
          ALL_COLORS[29],
          null,
          ALL_COLORS[29],
          null,
          ALL_COLORS[29],
          null,
        ],
      },
    ],
    repeaters: [{ count: 3, start: 3, length: 12 }],
  },
  {
    name: "Triple Stripes in Opposition",
    band: [
      {
        label: "H",
        colors: [
          ALL_COLORS[29],
          null,
          ALL_COLORS[29],
          null,
          ALL_COLORS[35],
          null,
          ALL_COLORS[29],
          null,
          ALL_COLORS[35],
          null,
          ALL_COLORS[29],
          null,
          ALL_COLORS[29],
        ],
      },
      {
        label: "U",
        colors: [
          null,
          ALL_COLORS[29],
          null,
          ALL_COLORS[35],
          null,
          ALL_COLORS[29],
          null,
          ALL_COLORS[29],
          null,
          ALL_COLORS[35],
          null,
          ALL_COLORS[29],
          null,
        ],
      },
    ],
    repeaters: [
      { count: 3, start: 3, length: 2 },
      { count: 3, start: 8, length: 2 },
      { count: 2, start: 3, length: 10 },
    ],
  },
  {
    name: "Adjacent Flowers",
    band: [
      {
        label: "H",
        colors: [
          ALL_COLORS[24],
          null,
          ALL_COLORS[24],
          null,
          ALL_COLORS[24],
          null,
          ALL_COLORS[25],
          null,
          ALL_COLORS[25],
          null,
          ALL_COLORS[41],
          null,
          ALL_COLORS[41],
          null,
          ALL_COLORS[24],
          null,
          ALL_COLORS[41],
          null,
          ALL_COLORS[41],
          null,
          ALL_COLORS[25],
          null,
          ALL_COLORS[25],
          null,
          ALL_COLORS[24],
          null,
          ALL_COLORS[24],
          null,
          ALL_COLORS[24],
        ],
      },
      {
        label: "U",
        colors: [
          null,
          ALL_COLORS[24],
          null,
          ALL_COLORS[25],
          null,
          ALL_COLORS[25],
          null,
          ALL_COLORS[24],
          null,
          ALL_COLORS[25],
          null,
          ALL_COLORS[25],
          null,
          ALL_COLORS[41],
          null,
          ALL_COLORS[41],
          null,
          ALL_COLORS[25],
          null,
          ALL_COLORS[25],
          null,
          ALL_COLORS[24],
          null,
          ALL_COLORS[25],
          null,
          ALL_COLORS[25],
          null,
          ALL_COLORS[24],
          null,
        ],
      },
    ],
    repeaters: [{ count: 2, start: 5, length: 14 }],
  },
  {
    name: "Flower Border",
    mode: "krokbragd",
    band: [
      {
        label: "H1",
        colors: [
          ALL_COLORS[34],
          null,
          ALL_COLORS[34],
          null,
          ALL_COLORS[34],
          null,
          null,
          ALL_COLORS[10],
          null,
          null,
          ALL_COLORS[10],
          null,
          null,
          ALL_COLORS[34],
          null,
          null,
          ALL_COLORS[34],
          null,
          null,
          ALL_COLORS[23],
          null,
          null,
          ALL_COLORS[34],
          null,
          ALL_COLORS[34],
          null,
          ALL_COLORS[34],
        ],
      },
      {
        label: "U2",
        colors: [
          null,
          ALL_COLORS[34],
          null,
          ALL_COLORS[34],
          null,
          null,
          ALL_COLORS[34],
          null,
          null,
          ALL_COLORS[34],
          null,
          null,
          ALL_COLORS[34],
          null,
          null,
          ALL_COLORS[34],
          null,
          null,
          ALL_COLORS[34],
          null,
          null,
          ALL_COLORS[34],
          null,
          ALL_COLORS[34],
          null,
          ALL_COLORS[34],
          null,
        ],
      },
      {
        label: "U3",
        colors: [
          null,
          null,
          null,
          null,
          null,
          ALL_COLORS[10],
          null,
          null,
          ALL_COLORS[19],
          null,
          null,
          ALL_COLORS[10],
          null,
          null,
          ALL_COLORS[23],
          null,
          null,
          ALL_COLORS[23],
          null,
          null,
          ALL_COLORS[23],
          null,
          null,
          null,
          null,
          null,
          null,
        ],
      },
    ],
    repeaters: [{ count: 4, start: 14, length: 3 }],
  },
  {
    name: "Traditional",
    mode: "krokbragd",
    band: [
      {
        label: "H1",
        colors: [
          ALL_COLORS[34],
          null,
          ALL_COLORS[34],
          null,
          ALL_COLORS[34],
          null,
          null,
          ALL_COLORS[34],
          null,
          null,
          ALL_COLORS[21],
          null,
          null,
          ALL_COLORS[21],
          null,
          null,
          ALL_COLORS[21],
          null,
          null,
          ALL_COLORS[10],
          null,
          null,
          ALL_COLORS[10],
          null,
          null,
          ALL_COLORS[10],
          null,
          null,
          ALL_COLORS[23],
          null,
          null,
          ALL_COLORS[23],
          null,
          null,
          ALL_COLORS[23],
          null,
          null,
          ALL_COLORS[10],
          null,
          null,
          ALL_COLORS[10],
          null,
          null,
          ALL_COLORS[10],
          null,
          null,
          ALL_COLORS[21],
          null,
          null,
          ALL_COLORS[21],
          null,
          null,
          ALL_COLORS[21],
          null,
          null,
          ALL_COLORS[34],
          null,
          ALL_COLORS[34],
          null,
          ALL_COLORS[34],
        ],
      },
      {
        label: "U2",
        colors: [
          null,
          ALL_COLORS[34],
          null,
          ALL_COLORS[34],
          null,
          null,
          ALL_COLORS[34],
          null,
          null,
          ALL_COLORS[34],
          null,
          null,
          ALL_COLORS[34],
          null,
          null,
          ALL_COLORS[21],
          null,
          null,
          ALL_COLORS[21],
          null,
          null,
          ALL_COLORS[21],
          null,
          null,
          ALL_COLORS[10],
          null,
          null,
          ALL_COLORS[10],
          null,
          null,
          ALL_COLORS[10],
          null,
          null,
          ALL_COLORS[10],
          null,
          null,
          ALL_COLORS[10],
          null,
          null,
          ALL_COLORS[21],
          null,
          null,
          ALL_COLORS[21],
          null,
          null,
          ALL_COLORS[21],
          null,
          null,
          ALL_COLORS[34],
          null,
          null,
          ALL_COLORS[34],
          null,
          null,
          ALL_COLORS[34],
          null,
          ALL_COLORS[34],
          null,
          ALL_COLORS[34],
          null,
        ],
      },
      {
        label: "U3",
        colors: [
          null,
          null,
          null,
          null,
          null,
          ALL_COLORS[21],
          null,
          null,
          ALL_COLORS[21],
          null,
          null,
          ALL_COLORS[10],
          null,
          null,
          ALL_COLORS[10],
          null,
          null,
          ALL_COLORS[10],
          null,
          null,
          ALL_COLORS[23],
          null,
          null,
          ALL_COLORS[23],
          null,
          null,
          ALL_COLORS[23],
          null,
          null,
          ALL_COLORS[34],
          null,
          null,
          ALL_COLORS[23],
          null,
          null,
          ALL_COLORS[23],
          null,
          null,
          ALL_COLORS[23],
          null,
          null,
          ALL_COLORS[10],
          null,
          null,
          ALL_COLORS[10],
          null,
          null,
          ALL_COLORS[10],
          null,
          null,
          ALL_COLORS[21],
          null,
          null,
          ALL_COLORS[21],
          null,
          null,
          null,
          null,
          null,
          null,
        ],
      },
    ],
    repeaters: [
      { count: 2, start: 5, length: 3 },
      { count: 2, start: 8, length: 3 },
      { count: 2, start: 17, length: 3 },
      { count: 2, start: 26, length: 3 },
      { count: 4, start: 29, length: 3 },
      { count: 2, start: 35, length: 3 },
      { count: 2, start: 44, length: 3 },
      { count: 3, start: 53, length: 3 },
    ],
  },
  {
    name: "Simple Sheep",
    mode: "krokbragd",
    band: [
      {
        label: "H1",
        colors: [
          ALL_COLORS[6],
          null,
          ALL_COLORS[6],
          null,
          ALL_COLORS[0],
          null,
          null,
          ALL_COLORS[6],
          null,
          null,
          ALL_COLORS[29],
          null,
          null,
          ALL_COLORS[29],
          null,
          null,
          ALL_COLORS[29],
          null,
          null,
          ALL_COLORS[25],
          null,
          null,
          ALL_COLORS[25],
          null,
          null,
          ALL_COLORS[23],
          null,
          null,
          ALL_COLORS[23],
          null,
          null,
          ALL_COLORS[23],
          null,
          null,
          ALL_COLORS[6],
          null,
          null,
          ALL_COLORS[0],
          null,
          null,
          ALL_COLORS[0],
          null,
          null,
          ALL_COLORS[0],
          null,
          null,
          ALL_COLORS[0],
          null,
          null,
          ALL_COLORS[0],
          null,
          null,
          ALL_COLORS[0],
          null,
          null,
          ALL_COLORS[0],
          null,
          null,
          ALL_COLORS[6],
          null,
          null,
          ALL_COLORS[6],
          null,
          null,
          ALL_COLORS[6],
          null,
          null,
          ALL_COLORS[6],
          null,
          null,
          ALL_COLORS[23],
          null,
          null,
          ALL_COLORS[23],
          null,
          null,
          ALL_COLORS[6],
          null,
          ALL_COLORS[0],
          null,
          ALL_COLORS[6],
        ],
      },
      {
        label: "U2",
        colors: [
          null,
          ALL_COLORS[6],
          null,
          ALL_COLORS[0],
          null,
          null,
          ALL_COLORS[6],
          null,
          null,
          ALL_COLORS[29],
          null,
          null,
          ALL_COLORS[29],
          null,
          null,
          ALL_COLORS[29],
          null,
          null,
          ALL_COLORS[25],
          null,
          null,
          ALL_COLORS[25],
          null,
          null,
          ALL_COLORS[23],
          null,
          null,
          ALL_COLORS[23],
          null,
          null,
          ALL_COLORS[0],
          null,
          null,
          ALL_COLORS[6],
          null,
          null,
          ALL_COLORS[6],
          null,
          null,
          ALL_COLORS[6],
          null,
          null,
          ALL_COLORS[6],
          null,
          null,
          ALL_COLORS[0],
          null,
          null,
          ALL_COLORS[0],
          null,
          null,
          ALL_COLORS[0],
          null,
          null,
          ALL_COLORS[0],
          null,
          null,
          ALL_COLORS[0],
          null,
          null,
          ALL_COLORS[23],
          null,
          null,
          ALL_COLORS[23],
          null,
          null,
          ALL_COLORS[23],
          null,
          null,
          ALL_COLORS[23],
          null,
          null,
          ALL_COLORS[23],
          null,
          null,
          ALL_COLORS[6],
          null,
          ALL_COLORS[0],
          null,
          ALL_COLORS[6],
          null,
        ],
      },
      {
        label: "U3",
        colors: [
          null,
          null,
          null,
          null,
          null,
          ALL_COLORS[6],
          null,
          null,
          ALL_COLORS[29],
          null,
          null,
          ALL_COLORS[29],
          null,
          null,
          ALL_COLORS[29],
          null,
          null,
          ALL_COLORS[25],
          null,
          null,
          ALL_COLORS[25],
          null,
          null,
          ALL_COLORS[23],
          null,
          null,
          ALL_COLORS[23],
          null,
          null,
          ALL_COLORS[23],
          null,
          null,
          ALL_COLORS[23],
          null,
          null,
          ALL_COLORS[23],
          null,
          null,
          ALL_COLORS[23],
          null,
          null,
          ALL_COLORS[23],
          null,
          null,
          ALL_COLORS[23],
          null,
          null,
          ALL_COLORS[23],
          null,
          null,
          ALL_COLORS[23],
          null,
          null,
          ALL_COLORS[23],
          null,
          null,
          ALL_COLORS[23],
          null,
          null,
          ALL_COLORS[23],
          null,
          null,
          ALL_COLORS[23],
          null,
          null,
          ALL_COLORS[23],
          null,
          null,
          ALL_COLORS[23],
          null,
          null,
          ALL_COLORS[23],
          null,
          null,
          ALL_COLORS[6],
          null,
          null,
          null,
          null,
          null,
          null,
        ],
      },
    ],
    repeaters: [],
  },
  {
    name: "Circles and Ovals",
    mode: "krokbragd",
    band: [
      {
        label: "H1",
        colors: [
          ALL_COLORS[24],
          null,
          ALL_COLORS[24],
          null,
          ALL_COLORS[24],
          null,
          null,
          ALL_COLORS[7],
          null,
          null,
          ALL_COLORS[7],
          null,
          null,
          ALL_COLORS[24],
          null,
          null,
          ALL_COLORS[24],
          null,
          null,
          ALL_COLORS[34],
          null,
          null,
          ALL_COLORS[34],
          null,
          null,
          ALL_COLORS[24],
          null,
          null,
          ALL_COLORS[24],
          null,
          null,
          ALL_COLORS[19],
          null,
          null,
          ALL_COLORS[19],
          null,
          null,
          ALL_COLORS[24],
          null,
          ALL_COLORS[24],
          null,
          ALL_COLORS[24],
        ],
      },
      {
        label: "U2",
        colors: [
          null,
          ALL_COLORS[24],
          null,
          ALL_COLORS[24],
          null,
          null,
          ALL_COLORS[7],
          null,
          null,
          ALL_COLORS[24],
          null,
          null,
          ALL_COLORS[7],
          null,
          null,
          ALL_COLORS[24],
          null,
          null,
          ALL_COLORS[24],
          null,
          null,
          ALL_COLORS[24],
          null,
          null,
          ALL_COLORS[24],
          null,
          null,
          ALL_COLORS[24],
          null,
          null,
          ALL_COLORS[19],
          null,
          null,
          ALL_COLORS[24],
          null,
          null,
          ALL_COLORS[19],
          null,
          ALL_COLORS[24],
          null,
          ALL_COLORS[24],
          null,
        ],
      },
      {
        label: "U3",
        colors: [
          null,
          null,
          null,
          null,
          null,
          ALL_COLORS[24],
          null,
          null,
          ALL_COLORS[24],
          null,
          null,
          ALL_COLORS[24],
          null,
          null,
          ALL_COLORS[24],
          null,
          null,
          ALL_COLORS[34],
          null,
          null,
          ALL_COLORS[24],
          null,
          null,
          ALL_COLORS[34],
          null,
          null,
          ALL_COLORS[24],
          null,
          null,
          ALL_COLORS[24],
          null,
          null,
          ALL_COLORS[24],
          null,
          null,
          ALL_COLORS[24],
          null,
          null,
          null,
          null,
          null,
          null,
        ],
      },
    ],
    repeaters: [
      { start: 8, length: 3, count: 2 },
      { start: 20, length: 3, count: 3 },
      { start: 32, length: 3, count: 4 },
    ],
  },
  {
    name: "Show Your Stripes: 1960-",
    band: [
      {
        label: "H",
        colors: [
          ALL_COLORS[29], // Aqua
          null,
          ALL_COLORS[31], // Delft
          null,
          ALL_COLORS[31],
          null,
          ALL_COLORS[31],
          null,
          ALL_COLORS[31],
          null,
          ALL_COLORS[31],
          null,
          ALL_COLORS[31],
          null,
          ALL_COLORS[31],
          null,
          ALL_COLORS[2], // Antique White
          null,
          ALL_COLORS[2],
          null,
          ALL_COLORS[1], // Cream
          null,
          ALL_COLORS[3], // Natural
          null,
          ALL_COLORS[2], // Antique White
          null,
          ALL_COLORS[18], // Light Peach
          null,
          ALL_COLORS[13], // Orchid Pink
          null,
          ALL_COLORS[1], // Cream
          null,
          ALL_COLORS[2], // Antique White
          null,
          ALL_COLORS[13], // Orchid Pink
          null,
          ALL_COLORS[14], // Copper Mist
          null,
          ALL_COLORS[39], // Soft Mauve
          null,
          ALL_COLORS[12], // Tomato
          null,
          ALL_COLORS[12],
          null,
          ALL_COLORS[11], // Bright Coral
          null,
          ALL_COLORS[12], // Tomato
          null,
          ALL_COLORS[11], // Bright Coral
          null,
          ALL_COLORS[12], // Tomato
          null,
          ALL_COLORS[11], // Bright Coral
          null,
          ALL_COLORS[8], // Burgundy
          null,
          ALL_COLORS[8],
          null,
          ALL_COLORS[8],
          null,
          ALL_COLORS[9], // Cardinal Red
          null,
          ALL_COLORS[8], // Burgundy
          null,
          ALL_COLORS[16], // Fudge Brown
          null,
        ],
      },
      {
        label: "U",
        colors: [
          null,
          ALL_COLORS[29], // Aqua
          null,
          ALL_COLORS[31], // Delft
          null,
          ALL_COLORS[31],
          null,
          ALL_COLORS[31],
          null,
          ALL_COLORS[31],
          null,
          ALL_COLORS[31],
          null,
          ALL_COLORS[31],
          null,
          ALL_COLORS[31],
          null,
          ALL_COLORS[2], // Antique White
          null,
          ALL_COLORS[2],
          null,
          ALL_COLORS[1], // Cream
          null,
          ALL_COLORS[3], // Natural
          null,
          ALL_COLORS[2], // Antique White
          null,
          ALL_COLORS[18], // Light Peach
          null,
          ALL_COLORS[13], // Orchid Pink
          null,
          ALL_COLORS[1], // Cream
          null,
          ALL_COLORS[2], // Antique White
          null,
          ALL_COLORS[13], // Orchid Pink
          null,
          ALL_COLORS[14], // Copper Mist
          null,
          ALL_COLORS[39], // Soft Mauve
          null,
          ALL_COLORS[12], // Tomato
          null,
          ALL_COLORS[12],
          null,
          ALL_COLORS[11], // Bright Coral
          null,
          ALL_COLORS[12], // Tomato
          null,
          ALL_COLORS[11], // Bright Coral
          null,
          ALL_COLORS[12], // Tomato
          null,
          ALL_COLORS[11], // Bright Coral
          null,
          ALL_COLORS[8], // Burgundy
          null,
          ALL_COLORS[8],
          null,
          ALL_COLORS[8],
          null,
          ALL_COLORS[9], // Cardinal Red
          null,
          ALL_COLORS[8], // Burgundy
          null,
          ALL_COLORS[16], // Fudge Brown
        ],
      },
    ],
    repeaters: [],
  },
];
