import { Color, PresetPattern } from "@/types/inkle";

export const ALL_COLORS: Color[] = [
  { name: "White", hex: "#FFFFFF", owned: true },
  { name: "Cream", hex: "#ebe6d4", owned: true },
  { name: "Antique White", hex: "#e7e2dd", owned: true },
  { name: "Natural", hex: "#D3D3D3", owned: true },
  { name: "Silver", hex: "#C0C0C0", owned: false },
  { name: "Stone", hex: "#818086", owned: false },
  { name: "Black", hex: "#000000", owned: true },
  { name: "Victory Red", hex: "#77142a", owned: true },
  { name: "Burgundy", hex: "#800020", owned: false },
  { name: "Cardinal Red", hex: "#C41E3A", owned: false },
  { name: "Atom Red", hex: "#E50C21", owned: false },
  { name: "Bright Coral", hex: "#FF4040", owned: false },
  { name: "Tomato", hex: "#FF6347", owned: false },
  { name: "Orchid Pink", hex: "#F4C2C2", owned: false },
  { name: "Copper Mist", hex: "#DA8A67", owned: false },
  { name: "Pumpkin", hex: "#FF7518", owned: false },
  { name: "Fudge Brown", hex: "#5C4033", owned: false },
  { name: "Taupe", hex: "#856a5e", owned: true },
  { name: "Light Peach", hex: "#FFE5B4", owned: false },
  { name: "Goldenrod", hex: "#f5ce56", owned: true },
  { name: "Golden Yellow", hex: "#FFDF00", owned: false },
  { name: "Maize", hex: "#FBEC5D", owned: false },
  { name: "Ecru", hex: "#C2B280", owned: false },
  { name: "Wasabi", hex: "#95aa64", owned: true },
  { name: "Frosty Green", hex: "#a9b79f", owned: true },
  { name: "Myrtle Green", hex: "#336621", owned: true },
  { name: "Forest Green", hex: "#228B22", owned: false },
  { name: "Mint Green", hex: "#98FB98", owned: false },
  { name: "Parakeet", hex: "#7FFFD4", owned: false },
  { name: "Aqua", hex: "#b1dbda", owned: true },
  { name: "Peacock", hex: "#0D98BA", owned: false },
  { name: "Delft", hex: "#a6b9db", owned: true },
  { name: "Dark Royal Blue", hex: "#002366", owned: false },
  { name: "Navy Blue", hex: "#101f4f", owned: true },
  { name: "Blue Hawaii", hex: "#375cad", owned: true },
  { name: "Medium Blue", hex: "#4F709C", owned: false },
  { name: "Violet", hex: "#8A2BE2", owned: false },
  { name: "Wood Violet", hex: "#856088", owned: false },
  { name: "Purple", hex: "#800080", owned: false },
  { name: "Soft Mauve", hex: "#E0889B", owned: false },
  { name: "Hot Pink", hex: "#FF69B4", owned: false },
  { name: "French Rose", hex: "#F64A8A", owned: false },
];

export const presetPatterns: PresetPattern[] = [
  {
    name: "Dots and Squares",
    band: [
      {
        label: "H",
        colors: [
          ALL_COLORS[20],
          null,
          ALL_COLORS[20],
          null,
          ALL_COLORS[30],
          null,
          ALL_COLORS[20],
          null,
          ALL_COLORS[30],
          null,
          ALL_COLORS[20],
        ],
      },
      {
        label: "U",
        colors: [
          null,
          ALL_COLORS[20],
          null,
          ALL_COLORS[20],
          null,
          ALL_COLORS[20],
          null,
          ALL_COLORS[20],
          null,
          ALL_COLORS[20],
          null,
        ],
      },
    ],
    repeaters: [
      { count: 2, start: 5, end: 7 },
      { count: 2, start: 7, end: 9 },
      { count: 2, start: 9, end: 11 },
      { count: 3, start: 3, end: 7 },
      { count: 3, start: 7, end: 11 },
    ],
  },
  {
    name: "Offset Bars",
    band: [
      {
        label: "H",
        colors: [
          ALL_COLORS[20],
          null,
          ALL_COLORS[30],
          null,
          ALL_COLORS[20],
          null,
          ALL_COLORS[20],
          null,
          ALL_COLORS[30],
          null,
          ALL_COLORS[20],
          null,
          ALL_COLORS[20],
        ],
      },
      {
        label: "U",
        colors: [
          null,
          ALL_COLORS[20],
          null,
          ALL_COLORS[20],
          null,
          ALL_COLORS[30],
          null,
          ALL_COLORS[20],
          null,
          ALL_COLORS[20],
          null,
          ALL_COLORS[20],
          null,
        ],
      },
    ],
    repeaters: [
      { count: 2, start: 0, end: 2 },
      { count: 5, start: 2, end: 4 },
      { count: 5, start: 4, end: 6 },
      { count: 5, start: 8, end: 10 },
    ],
  },
  {
    name: "False Checks with 2",
    band: [
      {
        label: "H",
        colors: [
          ALL_COLORS[20],
          null,
          ALL_COLORS[20],
          null,
          ALL_COLORS[30],
          null,
          ALL_COLORS[20],
          null,
          ALL_COLORS[20],
        ],
      },
      {
        label: "U",
        colors: [
          null,
          ALL_COLORS[20],
          null,
          ALL_COLORS[20],
          null,
          ALL_COLORS[30],
          null,
          ALL_COLORS[20],
          null,
        ],
      },
    ],
    repeaters: [
      { count: 2, start: 3, end: 5 },
      { count: 2, start: 5, end: 7 },
      { count: 4, start: 3, end: 7 },
    ],
  },
  {
    name: "True Checks with 3",
    band: [
      {
        label: "H",
        colors: [
          ALL_COLORS[20],
          null,
          ALL_COLORS[20],
          null,
          ALL_COLORS[30],
          null,
          ALL_COLORS[20],
          null,
          ALL_COLORS[30],
          null,
          ALL_COLORS[20],
        ],
      },
      {
        label: "U",
        colors: [
          null,
          ALL_COLORS[20],
          null,
          ALL_COLORS[20],
          null,
          ALL_COLORS[30],
          null,
          ALL_COLORS[20],
          null,
          ALL_COLORS[20],
          null,
        ],
      },
    ],
    repeaters: [
      { count: 3, start: 3, end: 5 },
      { count: 2, start: 3, end: 7 },
      { count: 3, start: 5, end: 7 },
      { count: 3, start: 7, end: 9 },
    ],
  },
  {
    name: "Triple Stripes",
    band: [
      {
        label: "H",
        colors: [
          ALL_COLORS[29],
          null,
          ALL_COLORS[29],
          null,
          ALL_COLORS[35],
          null,
          ALL_COLORS[35],
          null,
          ALL_COLORS[35],
          null,
          ALL_COLORS[29],
          null,
          ALL_COLORS[29],
          null,
          ALL_COLORS[29],
        ],
      },
      {
        label: "U",
        colors: [
          null,
          ALL_COLORS[29],
          null,
          ALL_COLORS[35],
          null,
          ALL_COLORS[35],
          null,
          ALL_COLORS[35],
          null,
          ALL_COLORS[29],
          null,
          ALL_COLORS[29],
          null,
          ALL_COLORS[29],
          null,
        ],
      },
    ],
    repeaters: [{ count: 3, start: 3, end: 15 }],
  },
  {
    name: "Triple Stripes in Opposition",
    band: [
      {
        label: "H",
        colors: [
          ALL_COLORS[29],
          null,
          ALL_COLORS[29],
          null,
          ALL_COLORS[35],
          null,
          ALL_COLORS[29],
          null,
          ALL_COLORS[35],
          null,
          ALL_COLORS[29],
          null,
          ALL_COLORS[29],
        ],
      },
      {
        label: "U",
        colors: [
          null,
          ALL_COLORS[29],
          null,
          ALL_COLORS[35],
          null,
          ALL_COLORS[29],
          null,
          ALL_COLORS[29],
          null,
          ALL_COLORS[35],
          null,
          ALL_COLORS[29],
          null,
        ],
      },
    ],
    repeaters: [
      { count: 3, start: 3, end: 5 },
      { count: 3, start: 8, end: 10 },
      { count: 2, start: 3, end: 13 },
    ],
  },
  {
    name: "Adjacent Flowers",
    band: [
      {
        label: "H",
        colors: [
          ALL_COLORS[24],
          null,
          ALL_COLORS[24],
          null,
          ALL_COLORS[24],
          null,
          ALL_COLORS[25],
          null,
          ALL_COLORS[25],
          null,
          ALL_COLORS[41],
          null,
          ALL_COLORS[41],
          null,
          ALL_COLORS[24],
          null,
          ALL_COLORS[41],
          null,
          ALL_COLORS[41],
          null,
          ALL_COLORS[25],
          null,
          ALL_COLORS[25],
          null,
          ALL_COLORS[24],
          null,
          ALL_COLORS[24],
          null,
          ALL_COLORS[24],
        ],
      },
      {
        label: "U",
        colors: [
          null,
          ALL_COLORS[24],
          null,
          ALL_COLORS[25],
          null,
          ALL_COLORS[25],
          null,
          ALL_COLORS[24],
          null,
          ALL_COLORS[25],
          null,
          ALL_COLORS[25],
          null,
          ALL_COLORS[41],
          null,
          ALL_COLORS[41],
          null,
          ALL_COLORS[25],
          null,
          ALL_COLORS[25],
          null,
          ALL_COLORS[24],
          null,
          ALL_COLORS[25],
          null,
          ALL_COLORS[25],
          null,
          ALL_COLORS[24],
          null,
        ],
      },
    ],
    repeaters: [{ count: 2, start: 5, end: 19 }],
  },
];
